### PR TITLE
Sagin, program 2

### PR DESCRIPTION
**Pull request by SaginAnil**

### CODE REVIEW

**Review by albinj12 — APPROVED** [review]
👍

**Comment by SaginAnil** [comment]
hey
so everything is done right? is there anything else i should do?

thank you

**Comment by albinj12** [comment]
Create the second PR only after merging the first one. :)

**Comment by SaginAnil** [comment]
but i have already submitted 4 programs? can i submit the 3rd and 4th
program again but as 3rd and 4th PR?

**Comment by albinj12** [comment]
It's better to submit any other 2 programs.

**Pull request merged**
