### PR TITLE
program 5 (binary search in ascending order)

### PR DESCRIPTION
**Pull request by osjohn01**

### CODE REVIEW

**Review by albinj12 — APPROVED** [review]
👍

**Comment by osjohn01** [comment]
How can I know that i have completed the Hacktoberfest challenge?

**Comment by albinj12** [comment]
Visit [hacktoberfest website](https://hacktoberfest.digitalocean.com). There you can view your PRs and see the status.

**Comment by osjohn01** [comment]
Okay. Thank You!

**Pull request merged**
