### PR TITLE
4 programs

### PR DESCRIPTION
**Pull request by laksh-glitch**

### CODE REVIEW

**Comment by laksh-glitch** [comment]
please ignore the first 3 programs

**Review by albinj12 — APPROVED** [review]
👍

**Comment by jamesjose03** [comment]
Please try to do the programs one by one. And try creating PR for each one @laksh-glitch

**Comment by jamesjose03** [comment]
You need 4 PRs for completing the HacktoberFest challenge

**Comment by jamesjose03** [comment]
You can try pushing random programs. Create PR for each

**Pull request merged**
