### PR TITLE
create program 1

### PR DESCRIPTION
**Pull request by SaginAnil**

### CODE REVIEW

**Review by jamesjose03 — APPROVED** [review]
👍

**Comment by jamesjose03** [comment]
Please make sure to write 3 more programs seperately and create 3 more PRs

**Comment by jamesjose03** [comment]
Congrats on your first PR 🎉

**Comment by SaginAnil** [comment]
hey
i have created the rest 3 programs and sent the pull request as a single
request, instead of separately for each, would that be an issue?

**Comment by SaginAnil** [comment]
hey i have solved it and send separate pull requests.

>

**Pull request merged**
